# Generated by Django 2.2 on 2020-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='Published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
