# Generated by Django 2.2 on 2020-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLib', '0002_auto_20200430_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='PagesNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
